//! CLDR data tables.
//!
//! Every submodule of `data` is generated by `locale-dev` and holds nothing
//! but static tables indexed by [`Locale`](crate::Locale). This file is
//! handwritten: it declares the submodules and the plain data types shared by
//! more than one of them. All formatting logic lives outside of `data`.

pub(crate) mod locales;

#[cfg(any(feature = "nums", feature = "datetime"))]
pub(crate) mod numbers;

#[cfg(feature = "datetime")]
pub(crate) mod dates;

#[cfg(feature = "currency")]
pub(crate) mod currency;

/// Digit grouping sizes of a number pattern, counted from the decimal point.
///
/// `#,##,##0` has a primary size of 3 and a secondary size of 2, so one
/// crore is written `1,00,00,000`. A primary size of 0 disables grouping.
#[cfg(any(feature = "nums", feature = "datetime"))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub struct Grouping {
    /// Size of the group closest to the decimal point.
    pub primary: u8,
    /// Size of every further group.
    pub secondary: u8,
}

/// Number symbols of a locale in its default numbering system.
#[cfg(any(feature = "nums", feature = "datetime"))]
#[derive(Debug, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub struct NumberSymbols {
    /// Decimal separator, e.g. `.` or `,`.
    pub decimal: &'static str,
    /// Grouping separator, e.g. `,`, `.` or a narrow no-break space.
    pub group: &'static str,
    /// Minus sign, which may carry bidi marks.
    pub minus_sign: &'static str,
    /// Grouping sizes of the standard decimal pattern.
    pub grouping: Grouping,
    /// Native digits `0` to `9`, or `None` for ASCII digits.
    pub digits: Option<&'static [char; 10]>,
}

#[cfg(any(feature = "nums", feature = "datetime"))]
impl NumberSymbols {
    /// Returns the number symbols of `locale`.
    pub fn for_locale(locale: crate::Locale) -> &'static Self {
        numbers::NUMBER_SYMBOLS[locale.index()]
    }
}
