//! Turns the [`Cldr`](crate::cldr::Cldr) model into the data modules of
//! `locale-rs` (`locale-rs/src/data/*.rs`).
//!
//! Items are built with `quote!` and laid out by `prettyplease`. Tables with
//! one entry per locale are written one entry per line with the locale as a
//! trailing comment, so a CLDR update produces a reviewable diff.

pub mod currency;
pub mod dates;
pub mod locales;
pub mod numbers;

use crate::error::Result;
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

/// Deduplicates values into `static` items. Interning the same tokens twice
/// returns the same item name.
pub struct Pool {
    prefix: &'static str,
    ty: TokenStream,
    names: HashMap<String, Ident>,
    items: Vec<TokenStream>,
}

impl Pool {
    pub fn new(prefix: &'static str, ty: TokenStream) -> Self {
        Self {
            prefix,
            ty,
            names: HashMap::new(),
            items: Vec::new(),
        }
    }

    /// Returns the name of the static holding `value`, creating it if needed.
    pub fn intern(&mut self, value: TokenStream) -> Ident {
        let key = value.to_string();
        if let Some(name) = self.names.get(&key) {
            return name.clone();
        }
        let name = format_ident!("{}_{}", self.prefix, self.items.len());
        let ty = &self.ty;
        self.items.push(quote! { static #name: #ty = #value; });
        self.names.insert(key, name.clone());
        name
    }

    pub fn len(&self) -> usize {
        self.items.len()
    }

    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    pub fn items(&self) -> TokenStream {
        let items = &self.items;
        quote! { #(#items)* }
    }
}

/// A generated Rust source file.
pub struct RustFile {
    doc: String,
    sections: Vec<String>,
}

impl RustFile {
    /// Starts a file with the generated-code banner and a module doc line.
    pub fn new(cldr_version: &str, doc: &str) -> Self {
        Self {
            doc: format!(
                "// @generated by locale-dev from CLDR {cldr_version}. Do not edit by hand;\n\
                 // run `cargo run -p locale-dev` instead.\n\n//! {doc}\n"
            ),
            sections: Vec::new(),
        }
    }

    /// Appends items, laid out by `prettyplease`.
    pub fn items(&mut self, tokens: TokenStream) -> Result<()> {
        let file: syn::File = syn::parse2(tokens)?;
        self.sections.push(prettyplease::unparse(&file));
        Ok(())
    }

    /// Appends `static NAME: [TY; N] = [...]` with one entry per locale, each
    /// line commented with its locale. Spacing is normalized by rustfmt.
    pub fn locale_table(
        &mut self,
        visibility: TokenStream,
        name: &str,
        element: TokenStream,
        rows: &[(&str, TokenStream)],
    ) {
        let mut out = format!(
            "{visibility} static {name}: [{element}; {}] = [\n",
            rows.len()
        );
        for (locale, value) in rows {
            out.push_str(&format!("    {value}, // {locale}\n"));
        }
        out.push_str("];\n");
        self.sections.push(out);
    }

    /// Writes the file. Formatting happens afterwards, see [`crate::format`].
    pub fn write(&self, path: &Path) -> Result<PathBuf> {
        let mut text = self.doc.clone();
        for section in &self.sections {
            text.push('\n');
            text.push_str(section);
        }
        fs::write(path, text)?;
        Ok(path.to_path_buf())
    }
}
